
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/snap/clion/250/bin/cmake/linux/x64/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:10 (project)"
    message: |
      The system is: Linux - 5.15.0-86-generic - x86_64
...
